# coding: utf-8
module TravelSky
  class Cities
    extend NameCodable
    
    def self.data
      "@akesu|阿克苏|AKU@aletai|阿勒泰|AAT@ankang|安康|AKA@anqing|安庆|AQG@anshan|鞍山|AOG@anshun|安顺|AVA@baise|百色|AEB@baoshan|保山|BSD@baotou|包头|BAV@beihai|北海|BHY@beijing|北京|PEK@bole|博乐|BQL@changbaishan|长白山|NBS@changchun|长春|CGQ@changde|常德|CGD@changdu|昌都|BPX@changhai|长海|CNI@changsha|长沙|CSX@changzhi|长治|CIH@changzhou|常州|CZX@chaoyang|朝阳|CHG@chengdu|成都|CTU@chifeng|赤峰|CIF@chongqing|重庆|CKG@dachuan|达川|DAX@dali|大理|DLU@dalian|大连|DLC@dandong|丹东|DDG@daqing|大庆|DQA@datong|大同|DAT@dehongmangshi|德宏芒市|LUM@diqingxianggelila|迪庆香格里拉|DIG@dongying|东营|DOY@dunhuang|敦煌|DNH@eerduosi|鄂尔多斯|DSN@enshi|恩施|ENH@erlianhaote|二连浩特|ERL@foshan|佛山|FUO@fuyang|阜阳|FUG@fuyun|富蕴|FYN@fuzhou|福州|FOC@ganzhou|赣州|GZH@geermu|格尔木|GOQ@guanghan|广汉|GHN@guangyuan|广元|GYS@guangzhou|广州|CAN@guilin|桂林|KWL@guiyang|贵阳|KWE@haerbin|哈尔滨|HRB@haikou|海口|HAK@hailaer|海拉尔|HLD@handan|邯郸|HDG@hangzhou|杭州|HGH@hanzhong|汉中|HZG@hefei|合肥|HFE@heihe|黑河|HEK@hengyang|衡阳|HNY@hetian|和田|HTN@huangshan|黄山|TXN@huhehaote|呼和浩特|HET@huizhou|惠州|HUZ@jiamusi|佳木斯|JMU@jian|吉安|KNC@jiayuguan|嘉峪关|JGN@jilin|吉林|JIL@jinan|济南|TNA@jingdezhen|景德镇|JDZ@jinggangshan|井冈山|JGS@jinghong|景洪|JHG@jining|济宁|JNG@jinzhou|锦州|JNZ@jiujiang|九江|JIU@jiuzhaihuanglong|九寨黄龙|JZH@jixi|鸡西|JXA@kanasi|喀纳斯|KJI@kangding|康定|KGT@kashi|喀什|KHG@kelamayi|克拉玛依|KRY@kuche|库车|KCA@kuerle|库尔勒|KRL@kunming|昆明|KMG@lanzhou|兰州|LHW@lasa|拉萨|LXA@liancheng|连城|LCX@lianyungang|连云港|LYG@libo|荔波|LLB@lijiang|丽江|LJG@lincang|临沧|LNJ@linyi|临沂|LYI@linzhi|林芝|LZY@liping|黎平|HZH@liuzhou|柳州|LZH@luoyang|洛阳|LYA@luzhou|泸州|LZO@manzhouli|满洲里|NZH@meixian|梅县|MXZ@mianyang|绵阳|MIG@mohe|漠河|OHE@mudanjiang|牡丹江|MDG@nalati|那拉提|NLT@nanchang|南昌|KHN@nanchong|南充|NAO@nanjing|南京|NKG@nanning|南宁|NNG@nantong|南通|NTG@nanyang|南阳|NNY@ningbo|宁波|NGB@panzhihua|攀枝花|PZI@puer|普洱|SYM@qianjiang|黔江|JIQ@qiemo|且末|IQM@qingdao|青岛|TAO@qingyang|庆阳|IQN@qinhuangdao|秦皇岛|SHP@qiqihaer|齐齐哈尔|NDG@quanzhou|泉州|JJN@quzhou|衢州|JUZ@sanya|三亚|SYX@shanghai|上海虹桥|SHA@shanghai|上海浦东|PVG@shantou|汕头|SWA@shashi|沙市|SHS@shenyang|沈阳|SHE@shenzhen|深圳|SZX@shijiazhuang|石家庄|SJW@suzhou|苏州|SZV@tacheng|塔城|TCG@taiyuan|太原|TYN@taizhou|台州|HYN@tengchong|腾冲|TCZ@tianjin|天津|TSN@tianshui|天水|THQ@tongchuan|铜仁|TEN@tongliao|通辽|TGO@wanzhou|万州|WXN@weifang|潍坊|WEF@weihai|威海|WEH@wenshan|文山|WNH@wenzhou|温州|WNZ@wuhai|乌海|WUA@wuhan|武汉|WUH@wuhu|芜湖|WHU@wulanhaote|乌兰浩特|HLH@wulumuqi|乌鲁木齐|URC@wuxi|无锡|WUX@wuyishan|武夷山|WUS@wuzhou|梧州|WUZ@xiamen|厦门|XMN@xian|西安|SIA@xiangfan|襄樊|XFN@xichang|西昌|XIC@xilinhaote|锡林浩特|XIL@xingtai|邢台|XNT@xingyi|兴义|ACX@xining|西宁|XNN@xuzhou|徐州|XUZ@yanan|延安|ENY@yancheng|盐城|YNZ@yanji|延吉|YNJ@yantai|烟台|YNT@yibin|宜宾|YBP@yichang|宜昌|YIH@yichun|伊春|LDS@yinchuan|银川|INC@yining|伊宁|YIN@yiwu|义乌|YIW@yongzhou|永州|LLF@yulin|榆林|UYN@yuncheng|运城|YCU@yushu|玉树|YUS@zhangjiajie|张家界|DYG@zhanjiang|湛江|ZHA@zhaotong|昭通|ZAT@zhengzhou|郑州|CGO@zhijiang|芷江|HJJ@zhongwei|中卫|ZHY@zhoushan|舟山|HSN@zhuhai|珠海|ZUH@zunyi|遵议|ZYI@beijing(CAPITAL)|北京首都|PEK@beijing(NANYUAN)|北京南苑|NAY@shanghai|上海|SHA"
    end
    
  end
end